package travel.model;
// Generated 16-Nov-2016 14:58:44 by Hibernate Tools 4.3.1

import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.FetchMode;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.CriteriaSpecification;
import org.hibernate.criterion.Restrictions;

/**
 * ImagedetailPosts generated by hbm2java
 */
public class ImagedetailPosts implements java.io.Serializable, InterfaceEntity {

    private Integer idImage;
    private Posts posts;

    public ImagedetailPosts() {
    }

    public ImagedetailPosts(Posts posts) {
        this.posts = posts;
    }

    public Integer getIdImage() {
        return this.idImage;
    }

    public void setIdImage(Integer idImage) {
        this.idImage = idImage;
    }

    public Posts getPosts() {
        return this.posts;
    }

    public void setPosts(Posts posts) {
        this.posts = posts;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ImagedetailPosts other = (ImagedetailPosts) obj;
        int id1 = this.idImage;
        int id2 = other.idImage;
        return (id1 == id2);
    }

    @Override
    public int add() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        if (this.posts != null) {
            try {
                tx = session.beginTransaction();
                this.idImage = (Integer) session.save(this);
                tx.commit();
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            }
        }
        session.close();
        return this.idImage;
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void delete() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        if (this.posts != null) {
            try {
                tx = session.beginTransaction();
                session.delete(this);
                tx.commit();
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            }
        }
        session.close();
    }

    @Override
    public String getJson() {
        String json = "";

        json += "{"
                + "\"idImage\":" + getIdImage() + ","
                + "\"idPosts\":" + getPosts().getIdPosts()
                + "}";

        return json;
    }
    public static ImagedetailPosts getImageDetailPostsId(int id) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria cr = session.createCriteria(ImagedetailPosts.class);
        cr.add(Restrictions.eq("idImage", id));
        List listLand = cr.list();
        if (listLand != null && !listLand.isEmpty()) {
            ImagedetailPosts temp = (ImagedetailPosts) listLand.get(0);
            session.close();
            return temp;
        } else {
            session.close();
            return null;
        }
    }
}
