package travel.model;
// Generated 16-Nov-2016 14:58:44 by Hibernate Tools 4.3.1

import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 * Rankingfestival generated by hbm2java
 */
public class Rankingfestival implements java.io.Serializable, InterfaceEntity {

    private RankingfestivalId id;
    private Festival festival;
    private User user;
    private int rank;

    public Rankingfestival() {
    }

    public Rankingfestival(RankingfestivalId id, Festival festival, User user, int rank) {
        this.id = id;
        this.festival = festival;
        this.user = user;
        this.rank = rank;
    }

    public RankingfestivalId getId() {
        return this.id;
    }

    public void setId(RankingfestivalId id) {
        this.id = id;
    }

    public Festival getFestival() {
        return this.festival;
    }

    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Rankingfestival other = (Rankingfestival) obj;

        return (this.id.getIdFestival() == other.id.getIdFestival() && this.id.getIdUser() == other.id.getIdUser());
    }

    @Override
    public int add() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        if (this.id != null) {
            Rankingfestival rf = getRankingFestivalById(this.id);
            if (rf == null) {
                try {
                    tx = session.beginTransaction();
                    session.save(this);
                    tx.commit();
                } catch (HibernateException e) {
                    if (tx != null) {
                        tx.rollback();
                    }
                    e.printStackTrace();
                }
            } else {
                try {
                    tx = session.beginTransaction();
                    session.update(this);
                    tx.commit();
                } catch (HibernateException e) {
                    if (tx != null) {
                        tx.rollback();
                    }
                    e.printStackTrace();
                }
            }
        }
        session.close();
        return 0;
    }

    @Override
    public void update() {
        if (this.id != null) {
            Session session = HibernateUtil.getSessionFactory().openSession();
            Transaction tx = null;
            try {
                tx = session.beginTransaction();
                session.update(this);
                tx.commit();
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            } finally {
                session.close();
            }
        }
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public static Rankingfestival getRankingFestivalById(RankingfestivalId id) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria cr = session.createCriteria(Rankingfestival.class);
        cr.add(Restrictions.eq("id", id));
        List listRankLand = null;
        try {
            listRankLand = cr.list();
        } catch (HibernateException e) {
            e.printStackTrace();
        }
        if (listRankLand != null && !listRankLand.isEmpty()) {
            Rankingfestival temp = (Rankingfestival) listRankLand.get(0);
            session.close();
            return temp;
        } else {
            session.close();
            return null;
        }
    }

    @Override
    public String getJson() {
        String json = "";

        json += "{"
                + "\"idUser\":" + getUser().getIdUser() + ","
                + "\"idFestival\":" + getFestival().getIdFestival() + ","
                + "\"rank\":" + getRank()
                + "}";

        return json;
    }

}
