package travel.model;
// Generated 16-Nov-2016 14:58:44 by Hibernate Tools 4.3.1

import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 * Rankinglandscape generated by hbm2java
 */
public class Rankinglandscape implements java.io.Serializable, InterfaceEntity {

    private RankinglandscapeId id;
    private Landscape landscape;
    private User user;
    private int rank;

    public Rankinglandscape() {
    }

    public Rankinglandscape(RankinglandscapeId id, Landscape landscape, User user, int rank) {
        this.id = id;
        this.landscape = landscape;
        this.user = user;
        this.rank = rank;
    }

    public RankinglandscapeId getId() {
        return this.id;
    }

    public void setId(RankinglandscapeId id) {
        this.id = id;
    }

    public Landscape getLandscape() {
        return this.landscape;
    }

    public void setLandscape(Landscape landscape) {
        this.landscape = landscape;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getRank() {
        return this.rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Rankinglandscape other = (Rankinglandscape) obj;

        return (this.id.getIdLandscape() == other.id.getIdLandscape() && this.id.getIdUser() == other.id.getIdUser());
    }

    @Override
    public int add() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Integer id = -2;
        if (this.id != null) {
            Rankinglandscape rl = getRankingLandscapeById(this.id);
            if (rl == null) {
                try {
                    tx = session.beginTransaction();
                    session.save(this);
                    tx.commit();
                } catch (HibernateException e) {
                    if (tx != null) {
                        tx.rollback();
                    }
                    e.printStackTrace();
                }
            } else {
                tx = session.beginTransaction();
                session.update(this);
                tx.commit();
            }
        }
        session.close();
        return id;
    }

    @Override
    public void update() {
        if (this.id != null) {

            Session session = HibernateUtil.getSessionFactory().openSession();
            Transaction tx = null;
            try {
                tx = session.beginTransaction();
                session.update(this);
                tx.commit();
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            } finally {
                session.close();
            }
        }
    }

    @Override
    public void delete() {
        if (this.id != null) {

            Session session = HibernateUtil.getSessionFactory().openSession();
            Transaction tx = null;
            try {
                tx = session.beginTransaction();
                session.delete(this);
                tx.commit();
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                e.printStackTrace();
            } finally {
                session.close();
            }
        }
    }

    public static Rankinglandscape getRankingLandscapeById(RankinglandscapeId id) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria cr = session.createCriteria(Rankinglandscape.class);
        List listRankLand = null;
        try {
            cr.add(Restrictions.eq("id", id));
            listRankLand = cr.list();
        } catch (HibernateException e) {
            e.printStackTrace();
        }
        if (listRankLand != null && !listRankLand.isEmpty()) {
            Rankinglandscape temp = (Rankinglandscape) listRankLand.get(0);
            session.close();
            return temp;
        } else {
            session.close();
            return null;
        }
    }

    @Override
    public String getJson() {
        String json = "";

        json += "{"
                + "\"idUser\":" + getUser().getIdUser() + ","
                + "\"idLandscape\":" + getLandscape().getIdLandscape() + ","
                + "\"rank\":" + getRank()
                + "}";

        return json;
    }

}
