package travel.model;
// Generated 16-Nov-2016 14:58:44 by Hibernate Tools 4.3.1

/**
 * RankingfestivalId generated by hbm2java
 */
public class RankingfestivalId implements java.io.Serializable {

    private int idFestival;
    private int idUser;

    public RankingfestivalId() {
    }

    public RankingfestivalId(int idFestival, int idUser) {
        this.idFestival = idFestival;
        this.idUser = idUser;
    }

    public int getIdFestival() {
        return this.idFestival;
    }

    public void setIdFestival(int idFestival) {
        this.idFestival = idFestival;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RankingfestivalId)) {
            return false;
        }
        RankingfestivalId castOther = (RankingfestivalId) other;

        return (this.getIdFestival() == castOther.getIdFestival())
                && (this.getIdUser() == castOther.getIdUser());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdFestival();
        result = 37 * result + this.getIdUser();
        return result;
    }

}
